version: '3.9'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - app_net
    volumes:
        - db:/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"  

networks:
  app_net:
      name: app_net
      external: true

volumes:
    db: {}