name: back-build-push

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create image tag
      run: echo "IMAGE_TAG=ghcr.io/ugenef/sol/back:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV && echo $IMAGE_TAG
    - name: Build the image
      run: docker build --file back/Sol.HttpApi/Dockerfile --tag ${{ env.IMAGE_TAG }} back
    - name: Login the registry
      run: docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_TOKEN }}
    - name: Push the image
      run: docker push ${{ env.IMAGE_TAG }}
    - name: Logout from the registry
      run: docker logout
