name: front-build-push

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create image tag
      run: echo "IMAGE_TAG=ghcr.io/${{ secrets.GHCR_USERNAME }}/sol/front:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build the image
      run: docker build --file front/Dockerfile --tag ${{ env.IMAGE_TAG }} --build-arg REACT_APP_BACK_BASE_URL=${{ secrets.BACK_URL }} --build-arg REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} front
    - name: Login the registry
      run: docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_TOKEN }}
    - name: Push the image
      run: docker push ${{ env.IMAGE_TAG }}
    - name: Logout from the registry
      run: docker logout
